Repository intel/neural-speed, pull requests merged in 2024-03, with the labels that each got.

#145 [Neural Speed] Support continuous batching + beam search inference in LLAMA
  developer_document.md
  neural_speed/__init__.py
  neural_speed/application/main_pybind.cpp
  neural_speed/core/ne.h
  neural_speed/models/gptj/gptj.cpp
  neural_speed/models/llama/llama.cpp
  neural_speed/models/llama/llama.h
  neural_speed/models/llama/llama_utils.cpp
  neural_speed/models/model_utils/model_config.h
  neural_speed/models/model_utils/model_types.h
  neural_speed/models/model_utils/model_utils.cpp
  scripts/python_api_example_for_model_server.py
  tests/test_model_server.py
Labels: documentation, enhancement, ready to merge

#143 2024.0 compatibility
  include/common/core/base_types.hpp
  include/common/core/common.hpp
  include/common/core/math_general.hpp
  include/common/core/memory.hpp
  tests/integration/data_transformer/common.hpp
  tests/utils/profiling.hpp
Labels: XeTLA

#118 [BesTLA] New thread pool and hybrid dispatcher
  .github/workflows/scripts/formatScan/clangtidy.sh
  CMakeLists.txt
  CMakePresets.json
  bestla/CMakeLists.txt
  bestla/bestla/bestla.h
  bestla/bestla/bestla_device.h
  bestla/bestla/bestla_parallel.h
  bestla/bestla/bestla_utils.h
  bestla/bestla/ut/bestla_benchmark.cpp
  bestla/bestla/ut/bestla_epilogue.cpp
  bestla/bestla/ut/bestla_gemm.cpp
  bestla/bestla/ut/bestla_parallel.cpp
  bestla/bestla/ut/bestla_prologue_a.cpp
  bestla/bestla/ut/bestla_prologue_b.cpp
  bestla/bestla/ut/bestla_ut.cpp
  bestla/bestla/ut/bestla_ut.h
  bestla/bestla/ut/bestla_wrapper.cpp
  bestla/bestla/ut/kernel_jit.cpp
  neural_speed/application/main_run.cpp
  neural_speed/cmake/Common.cmake
  neural_speed/core/CMakeLists.txt
  neural_speed/core/layers/bestla_common.hpp
  neural_speed/core/layers/ip_fusion_ffn.cpp
  neural_speed/core/layers/ip_fusion_qkv.cpp
  neural_speed/core/layers/mha_dense_wrapper.h
  neural_speed/core/layers/ne_bestla.cpp
  neural_speed/core/ne_bestla.h
  neural_speed/core/ne_layers.c
  neural_speed/models/model_utils/quant_utils.cpp
Labels: ready to merge, BesTLA

#159 DG2 supports for XeTLA SDP example
  .editorconfig
  CMakeLists.txt
  examples/01_gemm_universal/gemm_universal.cpp
  examples/02_basic_gemm/basic_gemm.cpp
  examples/03_gemm_relu_bias/gemm_relu_bias.cpp
  examples/04_gemm_polynomial/gemm_polynomial.cpp
  examples/05_batch_gemm/batch_gemm.cpp
  examples/05_batch_gemm/batch_gemm.hpp
  examples/06_gemm_softmax/gemm_softmax.cpp
  examples/07_multi_layer_perceptron/multi_layer_perceptron.cpp
  examples/08_scaled_dot_product_attention/scaled_dot_product_attention.cpp
  examples/08_scaled_dot_product_attention/softmax.hpp
  examples/10_gemm_large_n/gemm_large_n.cpp
  examples/11_stream_k_gemm/stream_k_gemm.cpp
  examples/CMakeLists.txt
  include/common/core/arch_config.hpp
  include/common/utils/common.hpp
  include/common/utils/raw_send_nbarrier.hpp
  include/experimental/group/gemm/compute_policy.hpp
  include/experimental/kernel/gemm/impl/int4_dequantize_kslicing_xe.hpp
  include/group/gemm/compute_policy.hpp
  include/group/gemm/impl/default_fpu_xe.hpp
  include/group/gemm/impl/default_xmx_xe.hpp
  include/group/gemm/impl/unaligned_xmx_xe.hpp
  include/kernel/default_config/common.hpp
  include/kernel/default_config/decision_tree_policy.hpp
  include/kernel/default_config/dummy_policy.hpp
  include/kernel/gemm/default_gemm.hpp
  include/kernel/gemm/gemm_preset.hpp
  include/kernel/gemm/impl/default_xe.hpp
  include/kernel/gemm/impl/kslicing_xe.hpp
  include/kernel/gemm/impl/stream_k_xe.hpp
  include/subgroup/tile/impl/payload_xe.hpp
  include/subgroup/tile/impl/prefetch_xe.hpp
  include/subgroup/tile/impl/tile_op_functor.hpp
  media/docs/construct_a_gemm.md
  tests/integration/default_config/group_gemm/kernel_func.hpp
  tests/integration/default_config/kernel_gemm/kernel_func.hpp
  tests/integration/gemm/bf16_stream_k/main.cpp
  tests/integration/gemm/fp16/common.hpp
  tests/integration/gemm/fp16/main.cpp
  tests/unit/tile_load_store/main.cpp
  tests/utils/execution.hpp
Labels: XeTLA

#169 [GPTQ Enhence] Support GPTQ for Baichuan2-13B & Falcon 7B & Phi-1.5
  docs/gptq_and_awq.md
  docs/supported_models.md
  neural_speed/__init__.py
  neural_speed/convert/__init__.py
  neural_speed/convert/common.py
  neural_speed/convert/convert_quantized_baichuan.py
  neural_speed/convert/convert_quantized_bloom.py
  neural_speed/convert/convert_quantized_falcon.py
  neural_speed/convert/convert_quantized_phi.py
  neural_speed/convert/convert_quantized_qwen.py
Labels: ready to merge

#177 [Model Enhence] Add Baichuan-7B architecutre and refactor Baichuan-13B.
  neural_speed/convert/convert_baichuan.py
  neural_speed/models/baichuan/baichuan.cpp
  neural_speed/models/baichuan/baichuan.h
  neural_speed/models/baichuan/baichuan_utils.cpp
  neural_speed/models/model_utils/model_files.h
Labels: enhancement, ready to merge

#156 [Neural Speed] Enable StableLM2-1.6B & StableLM2-Zephyr-1.6B & StableLM-3B
  docs/supported_models.md
  neural_speed/__init__.py
  neural_speed/application/CMakeLists.txt
  neural_speed/application/main_pybind.cpp
  neural_speed/application/whisper_pybind.cpp
  neural_speed/convert/__init__.py
  neural_speed/convert/convert_stablelm.py
  neural_speed/models/CMakeLists.txt
  neural_speed/models/model_utils/model_types.h
  neural_speed/models/stablelm/stablelm.cpp
  neural_speed/models/stablelm/stablelm.h
  neural_speed/models/stablelm/stablelm_utils.cpp
  scripts/convert.py
  scripts/run.py
  tests/model-test/cpp_graph_inference.sh
Labels: v1.0a

#172 [BesTLA] Improve RTN quantization accuracy of int4 and int3
  bestla/bestla/bestla.h
  bestla/bestla/bestla_device.h
  bestla/bestla/bestla_parallel.h
  bestla/bestla/bestla_prologue_b.h
  bestla/bestla/bestla_utils.h
  bestla/bestla/kernel_avx2.h
  bestla/bestla/kernel_avx512f.h
  bestla/bestla/kernel_ref.h
  bestla/bestla/kernel_wrapper.h
  bestla/bestla/ut/bestla_gemm.cpp
  bestla/bestla/ut/bestla_prologue_a.cpp
  bestla/bestla/ut/bestla_prologue_b.cpp
  bestla/bestla/ut/bestla_ut.h
  bestla/bestla/ut/kernel_intrin.cpp
  bestla/bestla/ut/kernel_wrapper.cpp
  neural_speed/application/common.cpp
  neural_speed/core/layers/bestla_gemm.cpp
  neural_speed/core/layers/mha_dense_wrapper.h
  neural_speed/models/model_utils/quant_utils.cpp
  neural_speed/models/whisper/whisper.cpp
Labels: ready to merge, v1.0a

#173 disable MHA_AVX2
  neural_speed/core/layers/mha_dense.cpp
Labels: ready to merge, v1.0a

#170 Python API extension tests for GPTQ
  neural_speed/convert/__init__.py
  neural_speed/convert/convert_quantized_phi.py
  neural_speed/models/requirements/baichuan13b-gptq.txt
  neural_speed/models/requirements/mixtral-gptq.txt
  scripts/python_api_example_for_gptq.py
  tests/model-test/cpp_graph_inference.sh
Labels: v1.0a

#180 mha enhance
  bestla/bestla/kernel_avx2.h
  neural_speed/core/layers/mha_dense.cpp
Labels: ready to merge

#182 [Model Enabling] Support ChatGLM3
  docs/prompt_template.md
  docs/supported_models.md
  neural_speed/__init__.py
  neural_speed/application/CMakeLists.txt
  neural_speed/application/main_pybind.cpp
  neural_speed/application/main_run.cpp
  neural_speed/convert/common.py
  neural_speed/convert/convert_chatglm.py
  neural_speed/models/CMakeLists.txt
  neural_speed/models/model_utils/gguf.h
  neural_speed/models/model_utils/model_types.h
  neural_speed/models/model_utils/model_utils.cpp
  scripts/inference.py
  scripts/run.py
  tests/model-test/cpp_graph_inference.sh
Labels: ready to merge
