Repository intel/neural-speed, pull requests merged in 2024-01, with the labels that each got.

#21 Fix pybind compile
  neural_speed/application/main_pybind.cpp
Labels: ready to merge

#27 test of python api
  .github/workflows/scripts/install_binary.sh
  .github/workflows/unit-test-llmruntime.yml
  .github/workflows/unitTest/env_setup.sh
  .github/workflows/unitTest/unittest_llmruntime.sh
  developer_document.md
  tests/test_python_api.py
Labels: v0.2, CI

#28 add cpp graph model test
  tests/model-test/calculate_percentiles.py
  tests/model-test/cpp_graph_inference.sh
  tests/model-test/cpp_graph_prompts.json
Labels: v0.2, CI

#39 Fix warmup prompt length and add ns_log_level control
  neural_speed/application/main_run.cpp
Labels: ready to merge

#40 [LLM Runtime] Support the GGUF format
  neural_speed/application/main_run.cpp
  neural_speed/convert/convert_chatglm.py
  neural_speed/convert/convert_llama.py
  neural_speed/models/model_utils/gguf.h
  neural_speed/models/model_utils/model_files.h
  requirements.txt
Labels: ready to merge

#31 add tests and nodes
  .github/workflows/cpp-graph-test.yml
  .github/workflows/unit-test-bestla.yml
  bestla/bestla/ut/bestla_ut.h
  bestla/bestla/ut/kernel_wrapper.cpp
Labels: ready to merge, v0.2, CI

#60 support double quant in BesTLA
  .gitignore
  bestla/bestla/bestla.h
  bestla/bestla/bestla_epilogue.h
  bestla/bestla/bestla_prologue_b.h
  bestla/bestla/bestla_storage.h
  bestla/bestla/bestla_utils.h
  bestla/bestla/kernel_avx2.h
  bestla/bestla/kernel_avx512f.h
  bestla/bestla/kernel_ref.h
  bestla/bestla/kernel_wrapper.h
  bestla/bestla/ut/bestla_prologue_b.cpp
  bestla/bestla/ut/bestla_ut.h
Labels: BesTLA

#48 [LLM Runtime] GGUF Enhencement
  README.md
  docs/supported_models.md
  neural_speed/__init__.py
  neural_speed/application/main_pybind.cpp
  neural_speed/convert/convert-hf-to-gguf.py
  neural_speed/convert/convert_chatglm.py
  neural_speed/convert/convert_llama.py
  neural_speed/core/data_types.h
  neural_speed/core/layers/vec_dot.h
  neural_speed/core/ne_layers.c
  neural_speed/models/bloom/bloom_utils.cpp
  neural_speed/models/falcon/falcon_utils.cpp
  neural_speed/models/llama/llama_utils.cpp
  neural_speed/models/model_utils/gguf.h
  neural_speed/models/model_utils/model_files.h
  neural_speed/models/mpt/mpt_utils.cpp
  neural_speed/models/starcoder/starcoder_utils.cpp
  neural_speed/vectors/cpu/quantize.h
  scripts/python_api_example_for_gguf.py
Labels: v0.2

#43 [Bestla] Fix for hybrid
  bestla/bestla/bestla_device.h
Labels: ready to merge

#73 fix BesTLA compile on Windows
  bestla/bestla/kernel_avx2.h
  bestla/bestla/kernel_avx512f.h
  bestla/bestla/ut/bestla_prologue_b.cpp
Labels: ready to merge, BesTLA

#71 fix ns log perf problem
  CMakeLists.txt
  README.md
  neural_speed/application/main_run.cpp
  neural_speed/models/llama/llama.cpp
  neural_speed/models/model_utils/model_utils.cpp
  neural_speed/models/model_utils/model_utils.h
Labels: bug, v0.2

#80 [LLM Runtime]Fixed straightforward-API issues
  scripts/inference.py
  scripts/quantize.py
  scripts/run.py
Labels: bug, v0.2

#81 uncomment print codes
  neural_speed/application/main_run.cpp
  neural_speed/models/llama/llama.cpp
Labels: ready to merge, v0.2

#76 refine readme
  README.md
  docs/advanced_usage.md
  docs/install.md
Labels: v0.2

#69 [Neural Speed] Cont Batching in Offline and Server (GPT-J & Beam Search First)
  .clang-tidy
  neural_speed/__init__.py
  neural_speed/application/main_pybind.cpp
  neural_speed/core/ne.h
  neural_speed/core/ne_layers.c
  neural_speed/core/ne_layers.h
  neural_speed/models/gptj/gptj.cpp
  neural_speed/models/gptj/gptj.h
  neural_speed/models/gptj/gptj_utils.cpp
  neural_speed/models/model_utils/model_config.h
  neural_speed/models/model_utils/model_types.h
  neural_speed/models/model_utils/model_utils.cpp
  neural_speed/models/model_utils/model_utils.h
  neural_speed/models/model_utils/pool.cpp
  neural_speed/models/model_utils/pool.h
  neural_speed/models/model_utils/scheduler.cpp
  neural_speed/models/model_utils/scheduler.h
  scripts/python_api_example_for_model_server.py
  tests/test_python_api.py
Labels: ready to merge

#92 [Neural Speed] Fix a blocker on Windows platforms
  scripts/inference.py
  scripts/quantize.py
Labels: ready to merge

#103 Optimization of Layernormalization
  bestla/CMakeLists.txt
  bestla/bestla/bestla_parallel.h
  bestla/bestla/kernel_avx2.h
  bestla/bestla/kernel_avx512f.h
  bestla/bestla/kernel_ref.h
  bestla/bestla/kernel_wrapper.h
  bestla/bestla/ut/kernel_wrapper.cpp
  neural_speed/core/layers/bestla_gemm.cpp
  neural_speed/core/layers/bestla_gemm.h
  neural_speed/core/layers/ne_bestla.cpp
  neural_speed/core/ne_bestla.h
  neural_speed/core/ne_layers.c
Labels: ready to merge, BesTLA
