Repository intel/neural-speed, pull requests merged in 2024-02, with the labels that each got.

#117 check isa for UT, use OMP as default
  CMakeLists.txt
  bestla/bestla/ut/kernel_wrapper.cpp
Labels: ready to merge

#109 Implement the YaRN rop scaling feature
  neural_speed/core/ne_layers.c
  neural_speed/core/ne_layers.h
Labels: ready to merge

#127 [GGUF Enhence] Support QWEN GGUF inference
  README.md
  docs/gguf.md
  docs/supported_models.md
  neural_speed/convert/convert-hf-to-gguf.py
  neural_speed/convert/convert_qwen.py
  neural_speed/models/qwen/qwen_utils.cpp
Labels: enhancement

#125 3bit weight infrastructure in BesTLA
  bestla/bestla/bestla.h
  bestla/bestla/bestla_prologue_b.h
  bestla/bestla/bestla_storage.h
  bestla/bestla/bestla_utils.h
  bestla/bestla/kernel_avx512f.h
  bestla/bestla/kernel_jit.h
  bestla/bestla/kernel_ref.h
  bestla/bestla/kernel_wrapper.h
  bestla/bestla/ut/bestla_prologue_b.cpp
  bestla/bestla/ut/kernel_jit.cpp
  neural_speed/convert/convert_quantized_gptj.py
  neural_speed/core/layers/bestla_gemm.cpp
  neural_speed/models/model_utils/quant_config.h
  neural_speed/models/model_utils/quant_utils.cpp
Labels: ready to merge, BesTLA

#136 Improvements Targeting Windows
  CMakeLists.txt
  neural_speed/application/audio_run.cpp
  neural_speed/application/common.cpp
  neural_speed/application/main_pybind.cpp
  neural_speed/application/main_run.cpp
  neural_speed/application/pybind_gptj.cpp
  neural_speed/application/whisper_pybind.cpp
  neural_speed/cmake/Common.cmake
  neural_speed/core/ne_layers.c
  neural_speed/models/baichuan/baichuan_utils.cpp
  neural_speed/models/model_utils/arg_parse.cpp
  neural_speed/models/model_utils/model_files.h
  neural_speed/models/model_utils/model_utils.cpp
  neural_speed/models/model_utils/model_utils.h
  neural_speed/models/model_utils/quant_utils.cpp
  neural_speed/models/model_utils/scheduler.cpp
  neural_speed/vectors/cpu/quantize.h
  requirements.txt
  scripts/perplexity.py
  setup.py
Labels: ready to merge
